routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

Route::group([
    'prefix' => 'adverts',
    'as' => 'adverts.',
    'namespace' => 'Advert',
    ], function () {
        Route::get('/show/{advert}', 'AdvertController@show')->name('show');
        Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
        //Route::get('/{category?}', 'AdvertController@index')->name('index');
        Route::post('/show/{advert}/comment', 'AdvertController@addComment')->name('addComment');
        Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
        \Illuminate\Support\Facades\Route::post('/users/{user}/block', 'UsersController@block')->name('users.block');

        \Illuminate\Support\Facades\Route::resource('regions', 'RegionsController');

        \Illuminate\Support\Facades\Route::resource('category-advert', 'CategoryAdvertController');

        //admin control category of adverts
        Route::group(['prefix' => 'category-advert/{category}', 'as' => 'category-advert.'], function () {
            Route::post('/first', 'CategoryAdvertController@first')->name('first');
            Route::post('/up', 'CategoryAdvertController@up')->name('up');
            Route::post('/down', 'CategoryAdvertController@down')->name('down');
            Route::post('/last', 'CategoryAdvertController@last')->name('last');
            Route::resource('attributes', 'CategoryAdvertAttributesController')->except('index');
        });
        //admin control commments
        Route::group(['prefix' => 'comment', 'as' => 'comments.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'CommentsController@index')->name('list');
            \Illuminate\Support\Facades\Route::get('/show/{comment}', 'CommentsController@show')->name('view');
            \Illuminate\Support\Facades\Route::delete('/delete/{comment}', 'CommentsController@delete')->name('delete');
            \Illuminate\Support\Facades\Route::post('/accepted/{comment}', 'CommentsController@accepted')->name('accepted');
        });

        Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'AdvertController@index')->name('list');
        });

        Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::get('/{ticket}/show', 'TicketController@show')->name('show');
            Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
            Route::put('/{ticket}/edit', 'TicketController@edit')->name('update');
            Route::post('{ticket}/message', 'TicketController@message')->name('message');
            Route::post('/{ticket}/close', 'TicketController@close')->name('close');
            Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
            Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
            Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
        });
    }
);

//user profile
//auth area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'middleware' => ['auth'],
        'namespace' => 'Cabinet',
    ],
    function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/update', 'ProfileController@update')->name('profile.update');
        Route::resource('advert', 'AdvertController')->except(['photoUpload']);
        Route::post('attributes','AdvertController@attributesByCategory')->name('attributes');

        Route::group(['prefix' => 'advert', 'as' => 'advert.'], function () {
            Route::post('/{advert}/send', 'AdvertController@send')->name('send');
            Route::post('/{advert}/close', 'AdvertController@close')->name('close');
            Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
        });


        Route::group(['prefix' => 'advert', 'as' => 'chat-message.'], function () {
            Route::post('/advert', 'ChatMessageController@advert')->name('advert');
        });


        Route::group(['prefix'=> 'advert/favorites','as'=>'favorites.'], function (){
            Route::get('/list', 'FavoritesController@index')->name('list');
            Route::post('/{advert}/add-favorites', 'FavoritesController@add')->name('add');
            Route::delete('/{advert}/remove-favorites', 'FavoritesController@remove')->name('remove');
        });

        Route::group(['prefix' => 'advert/{advert}', 'as'=>'advert.'], function (){
            Route::post('/photo-upload','AdvertPhotoController@upload')->name('photo.upload');
            Route::get('/list','AdvertPhotoController@index')->name('photo.list');
            Route::post('/delete','AdvertPhotoController@delete')->name('photo.delete');
        });

        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
    });

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Comment;
use App\Service\CommentService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentsController extends Controller
{
    protected $commentService;

    public function __construct(CommentService $commentService)
    {
        $this->commentService = $commentService;
    }

    public function index(Request $request)
    {
        $comments = $this->commentService->getList($request);

        //list statuses of users
        $statuses = Comment::getStatusList();

        //get list users
        return view('admin.comments.list', compact('comments', 'statuses'));
    }

    public function show(Comment $comment)
    {
        return view('admin.comments.show', compact('comment'));
    }

    public function delete(int $commentId)
    {
        $this->commentService->delete($commentId);

        return back();
    }

    public function accepted(int $commentId)
    {
        $this->commentService->accepted($commentId);

        return back();
    }
}

resources/views/admin/comments/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        @if(count($comments)>0)
            <table class="table-bordered table-striped table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Comment</th>
                    <th>Advert title</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($comments as $comment)
                    <tr>
                        <td>
                            {{ $comment->id }}
                        </td>
                        <td>
                            <a href="{{ route('admin.comments.view', $comment) }}">
                                {{ str_limit($comment->message, $limit = 100, $end = '...') }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('adverts.show', $comment->advert) }}"> {{ $comment->advert->title }} </a>
                        </td>
                        <td>
                            @if($comment->isDraft())
                                <span class="badge badge-secondary">{{$comment->getStatusLabel()}}</span>
                            @elseif($comment->isAccepted())
                                <span class="badge badge-primary">{{$comment->getStatusLabel()}}</span>
                            @endif
                            @if($comment->isBlocked())
                                <span class="badge badge-danger">{{$comment->getStatusLabel()}}</span>
                            @endif
                        </td>
                        <td>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{ $comments->links() }}
        @endif
    </div>
@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-9">

                <div class="row">
                    <label>Status: </label>
                    <strong>{{$comment->getStatusLabel()}}</strong>
                </div>

                <div class="row">
                    <label>
                        <strong>Text comment: </strong>
                    </label>


                    <p>{!! nl2br(e($comment->message)) !!}</p>
                </div>

                <div class="row">
                    <form method="POST" action="{{ route('admin.comments.delete', $comment) }}" class="mr-1">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-secondary">
                            <span class="fa fa-remove"></span> Delete
                        </button>
                    </form>

                    <form method="POST" action="{{ route('admin.comments.accepted', $comment) }}" class="mr-1">
                        @csrf
                        <button class="btn btn-danger">
                            <span class="fa fa-hand-o-up"></span> Accepted
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection