routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

Route::group([
    'prefix' => 'adverts',
    'as' => 'adverts.',
    'namespace' => 'Advert',
    ], function () {
        Route::get('/show/{advert}', 'AdvertController@show')->name('show');
        Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
        //Route::get('/{category?}', 'AdvertController@index')->name('index');
        Route::post('/show/{advert}/comment', 'AdvertController@addComment')->name('addComment');
        Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
        \Illuminate\Support\Facades\Route::post('/users/{user}/block', 'UsersController@block')->name('users.block');

        \Illuminate\Support\Facades\Route::resource('regions', 'RegionsController');

        \Illuminate\Support\Facades\Route::resource('category-advert', 'CategoryAdvertController');

        //admin control category of adverts
        Route::group(['prefix' => 'category-advert/{category}', 'as' => 'category-advert.'], function () {
            Route::post('/first', 'CategoryAdvertController@first')->name('first');
            Route::post('/up', 'CategoryAdvertController@up')->name('up');
            Route::post('/down', 'CategoryAdvertController@down')->name('down');
            Route::post('/last', 'CategoryAdvertController@last')->name('last');
            Route::resource('attributes', 'CategoryAdvertAttributesController')->except('index');
        });
        //admin control commments
        Route::group(['prefix' => 'comment', 'as' => 'comments.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'CommentsController@index')->name('list');
            \Illuminate\Support\Facades\Route::get('/show/{comment}', 'CommentsController@show')->name('view');
            \Illuminate\Support\Facades\Route::delete('/delete/{comment}', 'CommentsController@delete')->name('delete');
            \Illuminate\Support\Facades\Route::post('/accepted/{comment}', 'CommentsController@accepted')->name('accepted');
        });

        Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'AdvertController@index')->name('list');
        });

        Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::get('/{ticket}/show', 'TicketController@show')->name('show');
            Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
            Route::put('/{ticket}/edit', 'TicketController@edit')->name('update');
            Route::post('{ticket}/message', 'TicketController@message')->name('message');
            Route::post('/{ticket}/close', 'TicketController@close')->name('close');
            Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
            Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
            Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
        });
    }
);

//user profile
//auth area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'middleware' => ['auth'],
        'namespace' => 'Cabinet',
    ],
    function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/update', 'ProfileController@update')->name('profile.update');
        Route::resource('advert', 'AdvertController')->except(['photoUpload']);
        Route::post('attributes','AdvertController@attributesByCategory')->name('attributes');

        Route::group(['prefix' => 'advert', 'as' => 'advert.'], function () {
            Route::post('/{advert}/send', 'AdvertController@send')->name('send');
            Route::post('/{advert}/close', 'AdvertController@close')->name('close');
            Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
        });


        Route::group(['prefix' => 'advert', 'as' => 'chat-message.'], function () {
            Route::post('/advert', 'ChatMessageController@advert')->name('advert');
        });


        Route::group(['prefix'=> 'advert/favorites','as'=>'favorites.'], function (){
            Route::get('/list', 'FavoritesController@index')->name('list');
            Route::post('/{advert}/add-favorites', 'FavoritesController@add')->name('add');
            Route::delete('/{advert}/remove-favorites', 'FavoritesController@remove')->name('remove');
        });

        Route::group(['prefix' => 'advert/{advert}', 'as'=>'advert.'], function (){
            Route::post('/photo-upload','AdvertPhotoController@upload')->name('photo.upload');
            Route::get('/list','AdvertPhotoController@index')->name('photo.list');
            Route::post('/delete','AdvertPhotoController@delete')->name('photo.delete');
        });

        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
    });

app/Http/Controllers/Admin/TicketController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\TicketMessage;
use App\Http\Requests\Admin\Ticket\SearchRequest;
use App\Http\Requests\Cabinet\Ticket\MessageRequest;
use App\Http\Requests\Cabinet\Ticket\UpdateRequest;
use App\Service\TicketService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Entity\Ticket;
use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{
    protected $ticketService;

    public function __construct(TicketService $ticketService)
    {
        $this->ticketService = $ticketService;
    }

    public function index(SearchRequest $request)
    {
        $tickets = $this->ticketService->findAll($request);

        $statuses = Ticket::getStatusList();

        return view('admin.tickets.list', compact('tickets', 'statuses'));
    }

    public function show(Ticket $ticket)
    {
        //convert to json, for vuejs component
        $messages = json_encode($this->ticketService->renderMessagesByTicket($ticket));

        return view('admin.tickets.show', compact('ticket','messages'));
    }
    public function editForm(Ticket $ticket)
    {
        return view('admin.tickets.edit', compact('ticket'));
    }
    
    public function edit(UpdateRequest $request, Ticket $ticket)
    {
        try {
            $this->ticketService->edit($ticket->id, $request);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);
    }
    
    public function message(MessageRequest $request, Ticket $ticket)
    {
        try {
            $this->ticketService->message(Auth::id(), $ticket->id, $request);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.show', $ticket);
    }
    
    public function approve(Ticket $ticket)
    {
        try {
            $this->ticketService->approve(Auth::id(), $ticket->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);
    }
    
    public function close(Ticket $ticket)
    {
        try {
            $this->ticketService->close(Auth::id(), $ticket->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);
    }
    
    public function reopen(Ticket $ticket)
    {
        try {
            $this->ticketService->reopen(Auth::id(), $ticket->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);
    }
    
    public function destroy(Ticket $ticket)
    {
        try {
            $this->ticketService->removeByAdmin($ticket->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.index');
    }    
}

app/Http/Controllers/Cabinet/TicketController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Entity\Ticket;
use App\Http\Requests\Cabinet\Ticket\CreateRequest;
use App\Http\Requests\Cabinet\Ticket\MessageRequest;
use App\Service\TicketService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class TicketController extends Controller
{
    private $service;

    public function __construct(TicketService $service)
    {
        $this->service = $service;
    }
    public function index()
    {
        $tickets = Ticket::ByAuthor(Auth::user())->orderByDesc('updated_at')->paginate(20);
        return view('cabinet.tickets.index', compact('tickets'));
    }
    public function show(Ticket $ticket)
    {

        $this->checkAccess($ticket);

        //convert to json, for vuejs component
        $messages = json_encode($this->service->renderMessagesByTicket($ticket));

        return view('cabinet.tickets.show', compact('ticket', 'messages'));
    }
    public function create()
    {
        return view('cabinet.tickets.create');
    }
    public function store(CreateRequest $request)
    {
        try {
            $ticket = $this->service->create(Auth::id(), $request);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.show', $ticket);
    }
    public function message(MessageRequest $request, Ticket $ticket)
    {
        $this->checkAccess($ticket);

        try {
            $this->service->message(Auth::id(), $ticket->id, $request);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.show', $ticket);
    }
    public function destroy(Ticket $ticket)
    {
        $this->checkAccess($ticket);
        try {
            $this->service->removeByOwner($ticket->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.favorites.index');
    }
    private function checkAccess(Ticket $ticket): void
    {
        if (!Gate::allows('owner-ticket', $ticket)) {
            abort(403);
        }
    }
}

resources/views/admin/tickets/edit.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{ route('admin.tickets.update', $ticket) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="subject" class="col-form-label">Subject</label>
            <input id="subject" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" name="subject" value="{{ old('subject', $ticket->subject) }}" required>
            @if ($errors->has('subject'))
                <span class="invalid-feedback"><strong>{{ $errors->first('subject') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="message" class="col-form-label">Message</label>
            <textarea id="message" class="form-control{{ $errors->has('message') ? ' is-invalid' : '' }}" name="message" rows="10" required>{{ old('message', $ticket->message) }}</textarea>
            @if ($errors->has('message'))
                <span class="invalid-feedback"><strong>{{ $errors->first('message') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>

@endsection

resources/views/admin/tickets/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="card mb-3">
        <div class="card-header">Filter</div>
        <div class="card-body">
            <form action="?" method="GET">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">ID</label>
                            <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="user" class="col-form-label">User</label>
                            <input id="user" class="form-control" name="user" value="{{ request('user') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="status" class="col-form-label">Status</label>
                            <select id="status" class="form-control" name="status">
                                <option value=""></option>
                                @foreach ($statuses as $value => $label)
                                    <option value="{{ $value }}"{{ $value === request('status') ? ' selected' : '' }}>{{ $label }}</option>
                                @endforeach;
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br />
                            <button type="submit" class="btn btn-primary">Search</button>
                            <a href="?" class="btn btn-outline-secondary">Clear</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Subject</th>
            <th>User</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($tickets as $ticket)
            <tr>
                <td>{{ $ticket->id }}</td>
                <td>{{ $ticket->created_at }}</td>
                <td>{{ $ticket->updated_at }}</td>
                <td><a href="{{ route('admin.tickets.show', $ticket) }}" target="_blank">{{ $ticket->subject }}</a></td>
                <td>{{ $ticket->user->id }} - {{ $ticket->user->name }}</td>
                <td>
                    @if ($ticket->isOpen())
                        <span class="badge badge-danger">Open</span>
                    @elseif ($ticket->isApproved())
                        <span class="badge badge-primary">Approved</span>
                    @elseif ($ticket->isClosed())
                        <span class="badge badge-secondary">Closed</span>
                    @endif
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

    {{ $tickets->links() }}
@endsection

resources/views/admin/tickets/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex flex-row mb-3">

        <a href="{{ route('admin.tickets.edit', $ticket) }}" class="btn btn-primary mr-1">Edit</a>

        @if ($ticket->isOpen())
            <form method="POST" action="{{ route('admin.tickets.approve', $ticket) }}" class="mr-1">
                @csrf
                <button class="btn btn-success">Approve</button>
            </form>
        @endif

        @if (!$ticket->isClosed())
            <form method="POST" action="{{ route('admin.tickets.close', $ticket) }}" class="mr-1">
                @csrf
                <button class="btn btn-success">Close</button>
            </form>
        @endif

        @if ($ticket->isClosed())
            <form method="POST" action="{{ route('admin.tickets.reopen', $ticket) }}" class="mr-1">
                @csrf
                <button class="btn btn-success">Reopen</button>
            </form>
        @endif

        <form method="POST" action="{{ route('admin.tickets.destroy', $ticket) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>

    <div class="row">
        <div class="col-md-7">
            <table class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <th>ID</th>
                    <td>{{ $ticket->id }}</td>
                </tr>
                <tr>
                    <th>Created</th>
                    <td>{{ $ticket->created_at }}</td>
                </tr>
                <tr>
                    <th>Updated</th>
                    <td>{{ $ticket->updated_at }}</td>
                </tr>
                <tr>
                    <th>User</th>
                    <td><a href="{{ route('admin.users.show', $ticket->user) }}" target="_blank">{{ $ticket->user->name }}</a></td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        @if ($ticket->isOpen())
                            <span class="badge badge-danger">Open</span>
                        @elseif ($ticket->isApproved())
                            <span class="badge badge-primary">Approved</span>
                        @elseif ($ticket->isClosed())
                            <span class="badge badge-secondary">Closed</span>
                        @endif
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-header">
            {{ $ticket->subject }}
        </div>
        <div class="card-body">
            {!! nl2br(e($ticket->content)) !!}
        </div>
    </div>

    <ticket :allow-message="{{ (!$ticket->allowsMessages()) ? '0' : '1'}}" :ticket-id="{{ $ticket->id }}" route="{!! route('admin.tickets.message', $ticket) !!}" :data="{{ $messages }}"></ticket>

@endsection