routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

Route::group([
    'prefix' => 'adverts',
    'as' => 'adverts.',
    'namespace' => 'Advert',
    ], function () {
        Route::get('/show/{advert}', 'AdvertController@show')->name('show');
        Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
        //Route::get('/{category?}', 'AdvertController@index')->name('index');
        Route::post('/show/{advert}/comment', 'AdvertController@addComment')->name('addComment');
        Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
        \Illuminate\Support\Facades\Route::post('/users/{user}/block', 'UsersController@block')->name('users.block');

        \Illuminate\Support\Facades\Route::resource('regions', 'RegionsController');

        \Illuminate\Support\Facades\Route::resource('category-advert', 'CategoryAdvertController');

        //admin control category of adverts
        Route::group(['prefix' => 'category-advert/{category}', 'as' => 'category-advert.'], function () {
            Route::post('/first', 'CategoryAdvertController@first')->name('first');
            Route::post('/up', 'CategoryAdvertController@up')->name('up');
            Route::post('/down', 'CategoryAdvertController@down')->name('down');
            Route::post('/last', 'CategoryAdvertController@last')->name('last');
            Route::resource('attributes', 'CategoryAdvertAttributesController')->except('index');
        });
        //admin control commments
        Route::group(['prefix' => 'comment', 'as' => 'comments.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'CommentsController@index')->name('list');
            \Illuminate\Support\Facades\Route::get('/show/{comment}', 'CommentsController@show')->name('view');
            \Illuminate\Support\Facades\Route::delete('/delete/{comment}', 'CommentsController@delete')->name('delete');
            \Illuminate\Support\Facades\Route::post('/accepted/{comment}', 'CommentsController@accepted')->name('accepted');
        });

        Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
            \Illuminate\Support\Facades\Route::get('/', 'AdvertController@index')->name('list');
        });

        Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::get('/{ticket}/show', 'TicketController@show')->name('show');
            Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
            Route::put('/{ticket}/edit', 'TicketController@edit')->name('update');
            Route::post('{ticket}/message', 'TicketController@message')->name('message');
            Route::post('/{ticket}/close', 'TicketController@close')->name('close');
            Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
            Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
            Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
        });
    }
);

//user profile
//auth area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'middleware' => ['auth'],
        'namespace' => 'Cabinet',
    ],
    function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('/update', 'ProfileController@update')->name('profile.update');
        Route::resource('advert', 'AdvertController')->except(['photoUpload']);
        Route::post('attributes','AdvertController@attributesByCategory')->name('attributes');

        Route::group(['prefix' => 'advert', 'as' => 'advert.'], function () {
            Route::post('/{advert}/send', 'AdvertController@send')->name('send');
            Route::post('/{advert}/close', 'AdvertController@close')->name('close');
            Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
        });


        Route::group(['prefix' => 'advert', 'as' => 'chat-message.'], function () {
            Route::post('/advert', 'ChatMessageController@advert')->name('advert');
        });


        Route::group(['prefix'=> 'advert/favorites','as'=>'favorites.'], function (){
            Route::get('/list', 'FavoritesController@index')->name('list');
            Route::post('/{advert}/add-favorites', 'FavoritesController@add')->name('add');
            Route::delete('/{advert}/remove-favorites', 'FavoritesController@remove')->name('remove');
        });

        Route::group(['prefix' => 'advert/{advert}', 'as'=>'advert.'], function (){
            Route::post('/photo-upload','AdvertPhotoController@upload')->name('photo.upload');
            Route::get('/list','AdvertPhotoController@index')->name('photo.list');
            Route::post('/delete','AdvertPhotoController@delete')->name('photo.delete');
        });

        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
    });

app/Http/Controllers/Admin/AdvertController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Advert;
use App\Entity\CategoryAdvert;
use App\Entity\Region;
use App\Service\AdvertService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

class AdvertController extends Controller
{
    protected $advertService;

    public function __construct(AdvertService $advertService)
    {
        /** @var AdvertService advertService */
        $this->advertService = $advertService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //filtered adverts by author
        $adverts = Advert::with (['category', 'regions','author'])
            ->orderBy('created_at', 'DESC')
            ->paginate(50);

        return view('admin.advert.list', compact('adverts'));
    }

    public function send(Advert $advert)
    {

        try {
            $this->advertService->sendToModeration($advert->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert);
    }

    public function close(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        try {
            $this->advertService->close($advert->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert);
    }
}

app/Http/Controllers/Advert/AdvertController.php
<?php

namespace App\Http\Controllers\Advert;

use App\Entity\Advert;
use App\Entity\CategoryAdvert;
use App\Entity\Region;
use App\Http\Controllers\Controller;
use App\Http\Requests\Cabinet\Comment\CreateRequest;
use App\Http\Requests\Search\SearchAdvertRequest;
use App\Http\Router\AdvertsPath;
use App\Service\AdvertSearchService;
use App\Service\CommentService;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Exception;

class AdvertController extends Controller
{
    protected $searchService;
    protected $commentService;

    public function __construct(AdvertSearchService $advertSearchService, CommentService $commentService)
    {
        $this->searchService = $advertSearchService;
        $this->commentService = $commentService;
    }

    public function index(SearchAdvertRequest $request, AdvertsPath $path)
    {
        $region = $path->region;
        $category = $path->category;
        $result = $this->searchService->search($category, $region, $request, 20, $request->get('page', 1));

        $adverts = $result['adverts'];
        $regionsCounts = $result['groupCategoriesCounts'];
        $categoriesCounts = $result['groupRegionCounts'];


        $query = $region ? $region->children() : Region::roots();
        $regions = $query->orderBy('name')->getModels();
        $query = $category ? $category->children() : CategoryAdvert::whereIsRoot();
        $categories = $query->defaultOrder()->getModels();


        //filtered regions without adverts
//        $regions = array_filter($regions, function (Region $region) use ($regionsCounts) {
//            return isset($regionsCounts[$region->id]) && $regionsCounts[$region->id] > 0;
//        });

        //filtered category without adverts
//        $categories = array_filter($categories, function (CategoryAdvert $category) use ($categoriesCounts) {
//            return isset($categoriesCounts[$category->id]) && $categoriesCounts[$category->id] > 0;
//        });

        return view('advert.index', compact(
            'category', 'region',
            'categories', 'regions',
            'regionsCounts', 'categoriesCounts',
            'adverts'
        ));
    }

    public function phone(Advert $advert)
    {
        //TODO get phone author advert(user click on btn - and get to show phone number)
        return $advert->author->phone;
    }

    public function show(Advert $advert)
    {
        //if (!$advert->isActive()) {abort(403);}

        $user = Auth::user();

        return view('advert.show', compact('advert', 'user'));
    }

    public function addComment(CreateRequest $request, Advert $advert)
    {
        //user send comment for advert
        try{
            $this->commentService->create($advert->id, Auth()->user()->id, $request);
            $response = ['errors'=>'', 'msg'=>'Success comment sended'];
        }catch (Exception $exception){
            $response = ['errors'=>$exception->getMessage(), 'msg'=>'Have errors'];
        }
        return $response;
    }
}

app/Http/Controllers/Cabinet/AdvertController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Entity\Advert;
use App\Entity\CategoryAdvert;
use App\Entity\Region;
use App\Http\Middleware\IsFilledProfile;
use App\Http\Requests\Cabinet\Advert\CreateRequest;
use App\Service\AdvertService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Http\Controllers\Controller;
use Auth;
use App\Http\Requests\Cabinet\Photo\CreateRequest as PhotoCreateRequest;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class AdvertController extends Controller
{
    protected $advertService;

    public function __construct(AdvertService $advertService)
    {
        $this->middleware(IsFilledProfile::class);

        /** @var AdvertService advertService */
        $this->advertService = $advertService;
    }

    public function index()
    {
        //filtered adverts by author
        $adverts = Advert::with (['category', 'regions'])
            ->byAuthor (Auth::user ())
            ->orderBy('created_at', 'DESC')
            ->paginate(20);

        return view('cabinet.advert.list', compact('adverts'));
    }

    public function create()
    {
        $categoriesTree = CategoryAdvert::getCategoryTree ();

        $regionsTree = Region::getTree();

        return view('cabinet.advert.create', ['categoriesTree'=>$categoriesTree,'regionsTree'=>$regionsTree]);
    }

    public function send(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        try {
            $this->advertService->sendToModeration($advert->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert);
    }

    public function close(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        try {
            $this->advertService->close($advert->id);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert);
    }

    public function store(CreateRequest $request)
    {
        try {
            $advert = $this->advertService->create(
                Auth::id (),
                $request->get('region_id', null),
                $request->get('category_advert_id'),
                $request
            );
        } catch (ModelNotFoundException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()
            ->route('cabinet.advert.show', compact('advert'))
            ->with('Success', 'Success create advert');
    }

    public function show(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        $user = Auth::user();

        return view('advert.show', compact('advert', 'user'));
    }

    public function edit(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        $advert->load(['regions', 'category', 'values']);

        $regionsTree = Region::getTree(null, $advert->regions->id);

        $categoriesTree = CategoryAdvert::getCategoryTree ($advert->category->id);

        return view('cabinet.advert.edit', [
            'categoriesTree' => $categoriesTree,
            'regionsTree' => $regionsTree,
            'advert' => $advert,
            'attributes' => $advert->category->allAttributesWithValues($advert->category->allAttributes(), $advert),
        ]);
    }

    public function update(CreateRequest $request, Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        try {
            //update after validation data
            $this->advertService->update($advert->id, $request);
        }catch (ModelNotFoundException $e) {
            return back()->with('error', $e->getMessage());
        }

        return redirect()->route('cabinet.advert.show', compact('advert'));
    }

    public function destroy(Advert $advert)
    {
        if(!Gate::allows('owner-advert', $advert)){
            abort(403);
        }

        $advert->delete();

        return redirect()->route('cabinet.advert.index');
    }

    public function attributesByCategory(Request $request)
    {
        $category = CategoryAdvert::findOrFail($request->get('category'));

        return response()->json($category->allAttributes());
    }

    public function photoUpload(PhotoCreateRequest $request, Advert $advert)
    {
        $imageName = time().'.'.$request->photo->getClientOriginalExtension();

        $request->photo->move(public_path('photo'), $imageName);

        return response()->json(['success'=>'You have successfully upload image.']);
    }
}

resources/views/advert/index.blade.php
@extends('layouts.app')

@section('search')
    @include('partials.search', ['category' => $category, 'route' => '?'])
@endsection

@section('breadcrumbs', '')

@section('content')

    @if ($categories)
        <div class="card card-default mb-3">
            <div class="card-header">
                @if ($category)
                    Categories of {{ $category->name }}
                @else
                    Categories
                @endif
            </div>
            <div class="card-body pb-0" style="color: #aaa">
                <div class="row">
                    @foreach (array_chunk($categories, 3) as $chunk)
                        <div class="col-md-3">
                            <ul class="list-unstyled">
                                @foreach ($chunk as $current)
                                    <li>
                                        <a href="{{ route('adverts.index', array_merge(['adverts_path' => adverts_path($region, $current)], request()->all())) }}">{{ $current->name }}</a>
                                        ({{ $categoriesCounts[$current->id] ?? 0 }})
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

    @if ($regions)
        <div class="card card-default mb-3">
            <div class="card-header">
                @if ($region)
                    Regions of {{ $region->name }}
                @else
                    Regions
                @endif
            </div>
            <div class="card-body pb-0" style="color: #aaa">
                <div class="row">
                    @foreach (array_chunk($regions, 3) as $chunk)
                        <div class="col-md-3">
                            <ul class="list-unstyled">
                                @foreach ($chunk as $current)
                                    <li>
                                        <a href="{{ route('adverts.index', array_merge(['adverts_path' => adverts_path($current, $category)], request()->all())) }}">{{ $current->name }}</a>
                                        ({{ $regionsCounts[$current->id] ?? 0 }})
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-md-9">

            <div class="adverts-list">
                @foreach ($adverts as $advert)
                    <div class="advert">
                        <div class="row">
                            <div class="col-md-3">
                                <div style="height: 180px; background: #f6f6f6; border: 1px solid #ddd"></div>
                            </div>
                            <div class="col-md-9">
                                <span class="float-right">{{ $advert->price }}</span>
                                <div class="h4" style="margin-top: 0"><a href="{{ route('adverts.show', $advert) }}">{{ $advert->title }}</a></div>
                                <p>Region: <a href="">{{ $advert->region ? $advert->region->name : 'All' }}</a></p>
                                <p>Category: <a href="">{{ $advert->category->name }}</a></p>
                                <p>Date: {{ $advert->created_at }}</p>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            {{ $adverts->links() }}
        </div>
        <div class="col-md-3">
            <div
                    class="banner mb-3"
                    data-url=""
                    data-format="240x400"
                    data-category="{{ $category ? $category->id : '' }}"
            ></div>
        </div>
    </div>

@endsection

resources/views/advert/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">

        @if ($advert->isDraft())
            <div class="alert alert-danger">
                It is a draft advert.
            </div>
            @if ($advert->reject_reason)
                <div class="alert alert-danger">
                    Advert is rejected: {{ $advert->reject_reason }}
                </div>
            @endif
        @endif


        @can('owner-advert', $advert)
            <!-- manage advert for owner advert -->
            <div class="d-flex flex-row mb-3">
                <a href="{{ route('cabinet.advert.edit', $advert) }}" class="btn btn-primary mr-1">Edit advert</a>
                <a href="{{ route('cabinet.advert.photo.list', $advert) }}" class="btn btn-primary mr-1">Photos of advert</a>

                @if ($advert->isDraft())
                    <form method="POST" action="{{ route('cabinet.advert.send', $advert) }}" class="mr-1">
                        @csrf
                        <button class="btn btn-success">Publish</button>
                    </form>
                @endif
                @if ($advert->isActive())
                    <form method="POST" action="{{ route('cabinet.advert.close', $advert) }}" class="mr-1">
                        @csrf
                        <button class="btn btn-success">Close</button>
                    </form>
                @endif

                <form method="POST" action="{{ route('cabinet.advert.destroy', $advert) }}" class="mr-1">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">Delete</button>
                </form>
            </div>
        @endcan
        <div class="row">
            <div class="col-md-9">
                <p class="float-right" style="font-size: 36px;">{{ $advert->price }}$</p>
                <h1 style="margin-bottom: 10px">{{ $advert->title  }}</h1>
                <p>
                    @if ($advert->expires_at)
                        Date: {{ $advert->published_at }} &nbsp;
                    @endif
                    @if ($advert->expires_at)
                        Expires: {{ $advert->expires_at }}
                    @endif
                </p>

                <div style="margin-bottom: 20px">
                    <div class="row">
                        <div class="col-10">
                            <div style="height: 400px; background: #f6f6f6; border: 1px solid #ddd"></div>
                        </div>
                        <div class="col-2">
                            <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                            <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                            <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                            <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                        </div>
                    </div>
                </div>

                <p>{!! nl2br(e($advert->content)) !!}</p>


                <table class="table table-bordered">
                    <tbody>
                    @foreach ($advert->category->allAttributes() as $attribute)
                        <tr>
                            <th>{{ $attribute->name }}</th>
                            <td>{{ $advert->getValue($attribute->id) }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <p>Address: {{ $advert->address }}</p>

                <div style="margin: 20px 0; border: 1px solid #ddd">
                    <div id="map" style="width: 100%; height: 250px"></div>
                </div>

                <p style="margin-bottom: 20px">Seller: {{ $advert->author->name }}</p>


                @auth
                    <div class="d-flex flex-row mb-3">
                        <span class="btn btn-primary phone-button mr-1" data-source="{{ route('adverts.phone', $advert) }}">
                            <span class="fa fa-phone"></span>
                            <span class="number">Show Phone Number</span>
                        </span>

                        @if ($user->advertExistInFavorites($advert->id))
                            <form method="POST" action="{{ route('cabinet.favorites.remove', $advert) }}" class="mr-1">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-secondary">
                                    <span class="fa fa-star"></span> Remove from Favorites
                                </button>
                            </form>
                        @else
                            <form method="POST" action="{{ route('cabinet.favorites.add', $advert) }}" class="mr-1">
                                @csrf
                                <button class="btn btn-danger">
                                    <span class="fa fa-star"></span> Add to Favorites
                                </button>
                            </form>
                        @endif
                    </div>

                @endauth
                @auth
                    <comment-component
                            advert-id='{{$advert->id}}'
                            route='{{route("adverts.addComment", $advert)}}'>
                    </comment-component>

                @endauth

                @foreach($advert->comments as $comment)
                    @include('advert.comment.view', ['comment'=>$comment])
                @endforeach
            </div>
        </div>
    </div>
@endsection